services:
  web:
    image: node:23-alpine
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://api:4000
    working_dir: /app/packages/web
    command: pnpm dev
    volumes:
      - ./packages/web:/app/packages/web
      - ./packages/web/node_modules:/app/packages/web/node_modules

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
      - JWT_SECRET=your-secret-key
      - BLUESKY_SERVICE=https://bsky.social
    volumes:
      - ./packages/api:/app/packages/api
      - ./packages/api/node_modules:/app/packages/api/node_modules

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  api_node_modules:
