name = "chronopost-api"
main = "src/index.ts"
compatibility_date = "2024-03-09"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "chronopost"
database_id = "placeholder-id"

# Variable bindings
[vars]
BLUESKY_SERVICE = "https://bsky.social"
JWT_SECRET = "your-jwt-secret-here"

# Route settings
routes = [
  { pattern = "api.chronopost.example.com", custom_domain = true }
]

[env.production]
routes = [
  { pattern = "api.chronopost.example.com", custom_domain = true }
]
